name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    attributes: { label: What & Why, placeholder: Context and business benefit… }
    validations: { required: true }
